"""Initial migration.

Revision ID: 50fa4d591121
Revises: None
Create Date: 2015-08-06 16:57:30.111472

"""

# revision identifiers, used by Alembic.
revision = '50fa4d591121'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=True),
    sa.Column('queue', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.drop_table('activation')
    op.drop_table('delete_activation')
    op.drop_table('blacklist')
    op.drop_table('user_access')
    op.drop_table('novo_config')
    op.drop_table('log')
    op.drop_table('operator')
    op.drop_table('operator_configuration')
    op.drop_table('created_password')
    op.drop_table('alembic_version')
    op.drop_table('user')
    op.drop_table('user_group')
    op.drop_table('device')
    op.drop_table('operator_route')
    op.drop_table('email_list')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_list',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email_list_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('operator_route',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('operator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('rule', mysql.VARCHAR(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('device',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tac', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('manufacturer', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('model', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('os', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('capabilities', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('specification_link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('features', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('family', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('series', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('group', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('action', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('user_group',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_group_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('permissions', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('permissions', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('login_attempts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('logged_in', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('first_login', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('user_group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', mysql.VARCHAR(length=32), nullable=False),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('created_password',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('_password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'created_password_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('operator_configuration',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('operator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('capability', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('data', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('operator',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('apn', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('bearer', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('notification', mysql.TEXT(), nullable=True),
    sa.Column('pre_notification', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('log',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('request_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('data', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('novo_config',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('config_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('config_value', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('user_access',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('action', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('parameters', mysql.TEXT(), nullable=True),
    sa.Column('data', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'user_access_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('blacklist',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('value', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('delete_activation',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('delete_activation_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('msisdn', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('activation',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('imei', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('msisdn', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('channel', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('tac', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('operator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('device_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('device_manufacturer', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('device_model', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('device_os', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('provisioning_method', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('error', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('device_features', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('device_family', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('device_group', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('device_series', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bulk_id', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('job')
    ### end Alembic commands ###
